name:                strong-path
version:             1.1.1.0
github:              "wasp-lang/strong-path"
license:             MIT
author:              "Martin Sosic"
maintainer:          "sosic.martin@gmail.com"
copyright:           "2020 Martin Sosic"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis:            Strongly typed paths in Haskell.
category:            System, Filesystem, FilePath

description:         Replacement for a FilePath that enables you to handle filepaths in your code in a type-safe manner. You can specify at type level if they are relative, absolute, file, directory, posix, windows, and even to which file or directory they point to or are relative to.

tested-with: GHC == 8.10.7, GHC == 9.0.1  # lts-18.15, nightly-2021-10-29

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    # NOTE: Version bounds here and in tests are defined so that they cover the latest LTS snapshot
    #   (lts-18.15) (lower bounds) and the nightly snapshot defined in stack.yaml (upper bounds).
    #   Those two are also tested in the CI, and corresponding GHC versions are mentioned above
    #   in the tested-with field.
    #   In case you decide to cover a different LTS with the lower bounds,
    #   make sure to also update the CI to use the correct LTS for testing and also update
    #   tested-with field above.
    - path >=0.9 && <0.10
    - exceptions >=0.10 && <0.11
    - filepath >=1.4 && <1.5
    - template-haskell >=2.16 && <2.18

tests:
  strong-path-test:
    main:                TastyDiscoverDriver.hs 
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - strong-path
      - path
      - filepath
      - tasty >=1.4 && <1.5
      - tasty-hspec >=1.1 && <1.3
      - tasty-quickcheck >=0.10 && <0.11
      - tasty-discover >=4.2 && <4.3
      - hspec >=2.7 && <2.9

