name:                strong-path
version:             0.1.0.0
github:              "Martinsos/strong-path"
license:             BSD3
author:              "Martin Sosic"
maintainer:          "sosic.martin@gmail.com"
copyright:           "2020 Martin Sosic"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Strongly typed paths in Haskell.
# category:            System, Filesystem

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Martinsos/strong-path#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - path
    - exceptions
    - filepath

tests:
  strong-path-test:
    main:                TastyDiscoverDriver.hs 
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - strong-path
      - tasty
      - tasty-hspec
      - tasty-quickcheck
      - tasty-discover
      - path
      - filepath
